# Generated by Django 3.0.7 on 2020-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200607_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category name'),
        ),
    ]
