# Generated by Django 3.0.7 on 2020-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200612_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.Category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
