# Generated by Django 3.0.7 on 2020-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200609_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.Category', verbose_name='Catégorie'),
        ),
    ]
