# Generated by Django 3.0.7 on 2020-06-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200612_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['owner']},
        ),
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_favourite',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('healthy_product', 'unhealthy_product', 'owner'), name='unique_favourite'),
        ),
    ]
