# Generated by Django 3.0.7 on 2020-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200609_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='products.Category', verbose_name='Catégorie'),
        ),
    ]
