# Generated by Django 3.0.7 on 2020-06-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200609_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compared_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
        ),
    ]
